backend:
  name: github
  repo: vmanucharyan/segmentstream-docs
  branch: master # Branch to update (optional; defaults to master)
  site-domain: netlify.segmentstream.dev

publish_mode: editorial_workflow
media_folder: "media"

collections:
  - name: "bigquery"
    label: "BigQuery"
    folder: "_docs/bigquery"
    create: true
    slug: '{{ slug }}'
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: "datadestionations"
    label: "Data Destinations"
    folder: "_docs/bigquery"
    create: true
    slug: '{{ slug }}'
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: "datasources"
    label: "Data Sources"
    folder: "_docs/datasources"
    create: true
    slug: '{{ slug }}'
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'digitaldata'
    label: "Digital Data"
    folder: "_docs/digitaldata"
    create: true
    slug: '{{ slug }}'
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'body', label: 'Body', widget: 'markdown' }
