backend:
  name: github
  repo: vmanucharyan/segmentstream-docs
  branch: master # Branch to update (optional; defaults to master)
  site-domain: netlify.segmentstream.dev

publish_mode: editorial_workflow
media_folder: "media"
public_folder: "img/uploads"


collections:
  - name: "bigquery"
    label: "BigQuery"
    folder: "_docs/bigquery"
    create: true
    slug: '{{ slug }}'
    fields:
      - { name: 'layout', label: 'Layout', widget: 'string' }
      - { name: 'title', label: 'Title', widget: 'string' }
